version = 1

[install]
curl.pkg-path = "curl"
dosbox-x.pkg-path = "dosbox-x"
unzip.pkg-path = "unzip"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]

[vars]
ZIP_URI = "https://archive.org/download/msdos_Commander_Keen_1_-_Marooned_on_Mars_1990/Commander_Keen_1_-_Marooned_on_Mars_1990.zip"

[build.commander-keen]
command = '''
  mkdir -p $out/bin
  curl -sLO $ZIP_URI
  unzip $(basename $ZIP_URI) -d $out
  cat > $out/bin/commander-keen <<STR
$(which dosbox-x) -c "mount g $out/CKeen1" -c "g:" -c "KEEN1.EXE" -fastlaunch
STR
  chmod +x $out/bin/commander-keen
'''
description = "Commander Keen 1 - Marooned on Mars (1990) for DOSBox-X"
sandbox = "pure"
runtime-packages = ["dosbox-x"]
version = "0.0.1"
