version = 1

[install]
curl.pkg-path = "curl"
dosbox-x.pkg-path = "dosbox-x"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]

[vars]
ZIP_URI = "https://archive.org/download/msdos_Commander_Keen_1_-_Marooned_on_Mars_1990/Commander_Keen_1_-_Marooned_on_Mars_1990.zip"

[build.commander-keen-new]
command = '''
  mkdir -p $out/bin
  curl -sLO $ZIP_URI
  unzip $(basename $ZIP_URI) -d $out
  cat > $out/bin/commander-keen <<STR
dosbox-x -c "mount g $out/CKeen1" -c "g:" -c "KEEN1.EXE" -fastlaunch
STR
  chmod +x $out/bin/commander-keen
'''
